package com.email.email.common.Enum.mail;

public enum TemplateEmailType {
    ORDER_DELIVERED,
    ORDER_PROCESSING,
    ORDER_CONCLUDED,
    ORDER_CONFIRMED,
    AUTH_RESET_PASSWORD,
    AUTH_USER_CREATED,
    AUTH_USER_UPDATE,
    TRANSACTION_PROCESSING,
    TRANSACTION_CONCLUDED,
    TRANSACTION_REFUSED,
    TRANSACTION_CANCELED
}
